name: 'Quick ECR Push'
description: 'Push containers to ECR easily.'

branding:
  icon: 'arrow-up-right'  
  color: 'yellow'


inputs:

  aws_account_id:
    description: 'The account ID of the container registry.'
    required: true

  aws_region:
    description: 'The region the container registry is hosted in.'
    required: true

  platforms:
    description: 'The platforms to build images for, comma-separated. Valid options are linux/amd64 and linux/arm64.'
    required: true
    default: 'linux/amd64,linux/arm64'


runs:
  using: "composite"
  steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/github-actions-${{ github.event.repository.name }}
        aws-region: ${{ inputs.aws_region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ github.event.repository.name }}
        tags: |
          type=schedule,pattern=latest
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=ref,event=branch

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: ${{ inputs.platforms }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
